<a href="https://colab.research.google.com/github/koalalovepabro/Deep-Learning/blob/main/01_numpy_%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

* numpy는 내부적으로 C로 구현이 되어 있어요 ( 속도가 빠르다. )
* 수치 연산에 관련된 방대한 라이브러리가 존재한다.( with scipy )
* 일반 python을 이용한 연산보다 훨씬 빠르다.
* 배열 병렬 연산에 특화 되어 있다.

In [ ]:
# numpy로 만든 배열을 ndarray 라고 한다.
# 1. 일반 파이썬 리스트를 numpy 배열화

py_list = [1, 2, 3]
arr1 = np.array(py_list)
arr1

array([1, 2, 3])

In [ ]:
# type 확인
type(arr1)

numpy.ndarray

# 배열의 종류
1. 스칼라 (scalar)
  * 0 차원 데이터라고 한다.
  * 단순한 값
  * `scalar_val = 10`
2. 벡터 (vector)
  * 1차원 배열이라고 한다.
  * 스칼라가 연속적으로 모여있는 것.
  * `vector_val = [1, 2, 3]`
  * 벡터 내에 데이터가 `N`가 있으면 `N 차원 벡터`라고 한다.
3. 행렬 (matrix)
  * 2차원 배열이라고 한다.
  * 1차원 배열인 벡터가 여러 개 모여있는 것.
  * `matrix_val = [ [1,2,3], [4,5,6]]`
4. 텐서 (tensor)
  * 3차원 이상의 배열을 의미한다.
  * Tensorflow는 뭘까요...?
  * 텐서의 개념을 이용하면 모든 배열의 모양을 이야기 할 수 있다.
    * 스칼라 - 0 Rank Tensor
    * 벡터 - 1 Rank Tensor
    * 행렬 - 2 Rank Tensor

numpy에서는 숫자 배열을 만들기 위한 여러 가지 함수를 제공

# np.arange
* np.arange 함수는 파이썬의 range 함수와 매우 흡사

In [ ]:
arr = np.arange(10) # 0 ~ 9 까지 들어있는 숫자 배열을 생성
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

리스트와 배열의 차이
* 리스트는 파이썬에 존재하는 모든 것을 담아낼 수가 있다.
  * list -> `["hello", 10, 123.122, True]`
* 배열은 보통 숫자 데이터만 들어가 있을 때 배열이라고 합니다.

In [ ]:
np.arange(1, 10) # 1 ~ 9까지 들어있는 숫자 배열을 생성

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1, 10, 2) # 1부터 9까지 2씩 띄워가면서 숫자 배열 생성

array([1, 3, 5, 7, 9])

# 다차원 배열 만들기
* `np.arange` : 1차원 정수 배열 만들 때 사용
* `np.zeros` : 0 으로 채워진 0 벡터(zero-vector)를 만들 때 사용
* `np.ones` : 1로 채워진 1 벡터(one-vector)를 만들 때 사용
* `np.full` : 지정한 숫자로 채워진 벡터를 만들 때 사용

* zeros, ones, full 전부다 벡터 뿐만이 아닌, 텐서까지도 생성이 가능

In [ ]:
np.zeros(5) # 1차원 배열에 5개의 0을 채운다.

array([0., 0., 0., 0., 0.])

In [ ]:
# 지정한 차원 수 대로 0으로 채워진 텐서 만들기
np.zeros((3, 4, 5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

3 으로 채워진 텐서는 어떻게 만들까?

In [ ]:
np.ones((3, 4, 5)) * 3

array([[[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]],

       [[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]],

       [[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]]])

np.full을 사용해도 된다.

In [ ]:
np.full((3, 4, 5), 3) # 배열의 모양(shape), 채울 숫자

array([[[3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3]],

       [[3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3]],

       [[3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3]]])

# 단위 행렬 만들기
* `np.eye`
* 단위 행렬 : 대각선의 방향의 원소가 1이고, 나머지는 0인 행렬

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

# 구간 나누기 ( 사잇값 만들기 )
* np.linspace

In [ ]:
np.linspace(1, 10, 3) # 1부터 10까지 균등하게 3개의 숫자를 만든다. - 2개의 구간을 만든다.

array([ 1. ,  5.5, 10. ])

In [ ]:
np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

In [ ]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

# Random을 사용하기 위한 numpy
* 랜덤 배열은 딥러닝에서 매개변수( `가중치`, `편향` )를 초기화 하기 위해서 사용
* 딥러닝에서는 일반적으로 활성화 함수에 따라서 Xavier 초깃값, He 초깃값, 0.01 표준편차 정규분포 초깃값을 사용할 수 있다.

## np.random.rand
* 완전 랜덤 만들기 ( 정규분포나 균등분포가 아닌 완벽한 랜덤 )

In [ ]:
np.random.rand(2, 3) # 랜덤값을 채울 차원을 지정

array([[0.51410578, 0.96719079, 0.74759991],
       [0.91973376, 0.56918708, 0.85322999]])

## np.random.randn
* 정규분포 랜덤값 만들기

In [ ]:
np.random.randn(10)

array([ 0.05976575,  0.12797079,  1.57247806, -1.18925928, -0.61256343,
       -1.38137099,  0.00269853, -0.20808   ,  0.82982546,  1.59099926])

## np.random.uniform
* 균등분포 랜덤값 만들기

In [ ]:
np.random.uniform(1.0, 3.0, size=(4, 5)) # 1.0 ~ 3.0 까지 균등분포 랜덤값 생성

array([[2.16717471, 1.54893323, 2.61512805, 2.39170615, 1.30575199],
       [1.25317929, 1.35515407, 2.23650674, 2.28261435, 2.77421828],
       [1.7076782 , 2.72169013, 1.11701113, 1.58727896, 1.19416828],
       [1.67689728, 1.29142975, 2.77633013, 2.39279719, 2.28388891]])

# 정수 랜덤 샘플링 하기
* `np.random.choice`
* 랜덤 샘플링 : 일정한 범위 내에서 필요한 정수를 랜덤으로 추출
* 딥러닝에서는 `mini-batch`를 만들 때 사용합니다.

In [ ]:
np.random.choice(100, size=(3, 4)) # 기본은 중복을 허용 하면서 추출

array([[87, 64,  4, 62],
       [77, 62, 93, 75],
       [25, 33, 65, 50]])

In [ ]:
# 숫자 내에서 랜덤하게 추출할 수도 있지만, 배열 내에서 랜덤하게 추출할 수 있다.
arr = np.arange(1, 6)

np.random.choice(arr, size=(2, 2))

array([[1, 1],
       [1, 4]])

In [ ]:
np.random.choice(arr, size=(2, 2), replace=False) # replace가 False면 중복 추출 X

array([[3, 1],
       [5, 4]])

# 랜덤 정수 배열 만들기
* `np.random.randint`

In [ ]:
arr1 = np.random.randint(1, 100, size=(5, )) # 1차원 배열의 원소 5개에 1~100 사이의 랜덤값을 채운다.
arr1

array([38, 66, 10, 59, 94])

In [ ]:
arr2 = np.random.randint(1, 100, size=(5, 1)) # 2차원 배열에 랜덤 정수 채우기
arr2

array([[68],
       [28],
       [83],
       [72],
       [97]])

arr1과 arr2는 같은 배열일까요? `No`
* arr1은 1차원 배열, arr2는 2차원 배열

arr1과 arr2는 같은 **벡터**일까요? `Yes`
* arr1은 numpy에는 행벡터의 모양을 하고 있지만 실제로는 열벡터이다.
* arr2는 열의 수가 1개인 열벡터의 모양을 하고 있다.

대부분의 머신러닝 라이브러리( sklearn, tensorflow, pytoch, caffe 등 )는 기본적인 데이터 취급을 열벡터로 하기 때문에 2차원 배열 이상부터 취급이 가능하다.

2차원 데이터 이상부터 전치행렬 변환이 가능하다.

# axis 이해하기
axis : 축. 축이란? 데이터가 추가되는 방향

예를 들어 3차원 배열 (3, 4, 5)

* 3차원 배열에 추가되는건? 2차원 배열
* 2차원 배열에 추가되는건? 1차원 배열
* 1차원 배열에 추가되는건? 0차원 스칼라

In [ ]:
arr = np.arange(1, 37).reshape(3,4,3)
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]],

       [[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [ ]:
# axis : 축의 인덱스
# 위의 예에서는 3차원 배열이기 때문에 축이 3가지
# 2차원 배열이 추가되는 axis : 0
# 1차원 배열이 추가되는 axis : 1
# 0차원 스칼라가 추가되는 axis : 2

# 각 축별 최댓값(max) 뽑아내기
np.max(arr, axis=0)

array([[25, 26, 27],
       [28, 29, 30],
       [31, 32, 33],
       [34, 35, 36]])

In [ ]:
np.max(arr, axis=1)

array([[10, 11, 12],
       [22, 23, 24],
       [34, 35, 36]])

In [ ]:
np.max(arr, axis=2)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [ ]:
arr = np.random.randint(1, 37, size=(3,4,3))
arr

array([[[19, 16, 25],
        [31, 13, 29],
        [ 6,  9, 21],
        [23,  4, 21]],

       [[32, 25, 14],
        [25, 13,  4],
        [25, 17,  6],
        [ 2,  4, 11]],

       [[ 3, 29, 27],
        [ 4, 23,  3],
        [27, 12, 31],
        [ 9, 34, 25]]])

In [ ]:
np.max(arr, axis=0)


array([[32, 29, 27],
       [31, 23, 29],
       [27, 17, 31],
       [23, 34, 25]])

In [ ]:
np.max(arr, axis=1)


array([[31, 16, 29],
       [32, 25, 14],
       [27, 34, 31]])

In [ ]:
np.max(arr, axis=2)

array([[25, 31, 21, 23],
       [32, 25, 25, 11],
       [29, 23, 31, 34]])

# 인덱스와 슬라이싱

In [ ]:
arr = np.arange(1, 11).reshape(2, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr[0]

array([1, 2, 3, 4, 5])

In [ ]:
arr[0][2]

3

In [ ]:
arr[0, 2]

3

특장 차원의 배열을 전체 선택하기 위해서 쓰는 연산자 `:`

In [ ]:
arr[:, 2]

array([3, 8])

In [ ]:
arr = np.arange(1, 37).reshape(3,4,3)
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]],

       [[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [ ]:
# [[16, 17, 18],
#  [19, 20, 21]]

arr[1, 1:3]

array([[16, 17, 18],
       [19, 20, 21]])

In [ ]:
arr[:, 1:3, 0:2]

array([[[ 4,  5],
        [ 7,  8]],

       [[16, 17],
        [19, 20]],

       [[28, 29],
        [31, 32]]])

In [ ]:
arr = np.arange(36).reshape(2,3,3,2)
arr

array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]]],


       [[[18, 19],
         [20, 21],
         [22, 23]],

        [[24, 25],
         [26, 27],
         [28, 29]],

        [[30, 31],
         [32, 33],
         [34, 35]]]])

In [ ]:
arr[0, :, :, 0]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [ ]:
# 3차원, 0차원 제외하고 1, 2차원 데이터 전체를 가지고 오고 싶다.
# 스프레드 연산자(...)
arr[0, ..., 0] # 3차원과 0차원 사이에 있는 모든 데이터를 선택

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

# 배열의 차원과 형상
* 형상(`shape`)
* 차원수(`ndim`)

In [ ]:
arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
arr.shape

(3, 4)

In [ ]:
arr.ndim

2

# 차원수 확장하기
* 보통 기초 딥러닝에서 이미지 분석을 위한 `CNN`을 활용할 때 데이터를 전처리하기 위해 사용된다.
* tensorflow는 `tf.newaxis`, numpy는 `np.newaxis`를 활용해서 추가 차원을 만들어 낼 수 있다.

---
tensorflow에서 CNN을 위한 이미지 데이터의 형태는 항상 `(N, H, W, C)`를 유지한다.

* `N` : `BATCH_SIZE` ( 이미지의 개수 )
* `H` : 이미지의 세로 픽셀 ( 세로 크기 )
* `W` : 이미지의 가로 픽셀 ( 가로 크기 )
* `C` : 이미지의 채널 수( 컬러이미지 RGB : 3, 흑백이미지 GRAYSCALE : 1 )

여러분들이 이미지를 크롤링을 했어요. 만약에 이미지가 흑백 이미지 라면 가로, 세로 크기 밖에 없어요 (`H`, `W`)로 이루어진 2차원 배열입니다. 이걸 4차원 배열 형태로 바꿔줘야만 해요

In [ ]:
arr = np.arange(784).reshape(28, 28)
arr.shape

(28, 28)

`(28, 28)`은 2차원 배열  -> `(H, W)`만 존재하는 경우이다. 이를 4차원 형태로 강제로 만들어 줘야 `CNN` 레이어에 입력이 가능하다. `(1, 28, 28, 1)`

In [ ]:
temp_arr = arr[np.newaxis, :, :, np.newaxis]
temp_arr.shape

(1, 28, 28, 1)

In [ ]:
# 또는
temp_arr2 = arr[np.newaxis, ..., np.newaxis]
temp_arr2.shape

(1, 28, 28, 1)

# 차원 쥐어 짜기
* `np.squeeze`
* 개수가 1인 차원의 내용을 없애는 기법

In [ ]:
temp_squeeze = np.squeeze(temp_arr)
temp_squeeze.shape

(28, 28)

# 배열의 형상(shape) 바꾸기
* `np.newaxis`를 활용하면 축을 하나 추가하게 된다.( 차원 수를 늘린다. )
* `np.squeeze`를 활용하면 개수가 1인 차원의 데이터를 삭제 ( 차원 수를 줄인다. )

평탄화
* `ravel` : 원본 배열을 평탄화 시킨 **참조**배열을 만들어 낸다. ( 이를 View 또는 Reference 라고 한다. )
* `flatten` : 원본 배열을 평탄화 시킨 **복사된**배열을 만들어 낸다.

* `ravel`은 원본의 배열에 수정이 가해질 가능성이 있고, `flatten`은 원본 배열에 영향을 미치지 않는다.

## ravel

In [ ]:
x = np.arange(15).reshape(3, 5)
x.shape

(3, 5)

In [ ]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
temp = np.ravel(x)
temp.shape

(15,)

In [ ]:
temp # 1차원 배열을 새롭게 만든게 아닌, 원본 2차원 배열을 1차원 배열 처럼 보이게만 만들어졌음.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
temp[0] = 100
temp

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

In [ ]:
x

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

## flatten

In [ ]:
# flatten은 ravel과 다르게 실제 1차원 배열을 새롭게 만들어 낸다.
x = np.arange(15).reshape(3, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
temp_flatten = x.flatten()
temp_flatten

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
temp_flatten[0] = 100 # flatten을 사용하면 새롭게 배열을 만들어냈기 때문에 원본 x에는 영향을 미치지 않는다.
temp_flatten

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

In [ ]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

데이터를 조금 더 안전하게 관리해야 하기 때문에 ravel보다는 flatten을 더 많이 쓴다.

## reshape

In [ ]:
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

reshape 팁 : reshape 함수 내의 모든 숫자를 곱했을 때 스칼라 원소의 개수와 같기만 하면 형상 변환이 가능하다.

In [ ]:
x.reshape(2,5,2) # 가능

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

-1을 reshape에 넣으면 남는 숫자를 자동으로 계산해 준다.

In [ ]:
x.reshape(2,-1,2) # -1이 5로 자동으로 지정된다.

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [ ]:
x.reshape(2,2,-1).shape

(2, 2, 5)

In [ ]:
x.reshape(2,3,-1).shape # 안됨.

ValueError: ignored

In [ ]:
x.reshape(2, -1, -1).shape # 안됨. -1은 하나만 쓸 수가 있어요. 뭐가 어떻게 지정될지 어떻게 알아요 ㅠㅠ

In [ ]:
x.size # 스칼라 원소의 개수 구하기

# 브로드 캐스팅
* 차원 수가 다른 배열끼리의 연산
* 차원이 달라도 0차원 스칼라의 개수가 똑같으면 연산이 가능
* 저차원의 배열을 고차원으로 **확장**
* 수학적으로는 고차원 배열의 shape과 똑같은 일벡터를 만들어서 저차원 배열과 곱한 배열을 만들어 계산

In [ ]:
x = np.arange(20).reshape(4, 5)
y = np.arange(20, 40).reshape(4, 5)

x.shape, y.shape

In [ ]:
x + y

In [ ]:
x * 2

In [ ]:
# shape이 다를 때의 연산
a = np.arange(12).reshape(4, 3)   # (4, 3)
b = np.arange(100, 103)           # (3, )
c = np.arange(1000, 1004)         # (4, )
d = b.reshape(1, 3)               # (1, 3)
e = np.arange(0, 4).reshape(4, 1) # (4, 1)

In [ ]:
a + b

In [ ]:
a + c # 안됨

ValueError: ignored

In [ ]:
a + d # 됨

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [ ]:
a + e # 됨

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

# 전치행렬 만들기
* 행렬 A의 행과 열의 인덱스를 바꾼 것을 전치행렬 이라고 한다.
* $A_{(i, j)}$의 위치를 $A_{(j, i)}$로 바꾼 것
* 보통 Transpose했다고 이야기 한다.

In [ ]:
A = np.arange(6).reshape(2, 3)
A

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
# ndarray에서 T만 호출해 주면 전치행렬 완성
A.T

array([[0, 3],
       [1, 4],
       [2, 5]])

나중에 역전파 할 때 사용됩니다